apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: miraccan/flaskvaultapp:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: VAULT_ADDR
          value: "https://vault:8200"
        - name: VAULT_TOKEN
          value: "hvs.HyQumksPbSrZqHBeRgh2f28h"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"